django3/day01/app/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from app import views

urlpatterns = [
   # 登录视图
    url(r'^login/$', views.login, name='login'),
    # 注册视图
    url(r'^register/$', views.register, name='register'),
    # 注销视图
    url(r'^logout/$', views.logout, name='logout'),
    # 手动实现登录注册注销
    url(r'^my_register/$', views.my_register, name='my_register'),

    url(r'^my_login/$', views.my_login, name='my_login'),

    url(r'^my_logout/$', views.my_logout, name='my_logout'),



    # 首页 login_required 登录检测
    url(r'index/', views.index, name='index'),
    # 导航栏
    url(r'left/', views.left, name='left'),
    # 班级
    url(r'^grade/$', views.grade, name='grade'),
    # 头部
    url(r'head/', views.head, name='head'),
    # 学生页面
    url(r'student/', views.student, name='student'),
    # 添加学生
    url(r'addstu/', views.addstu, name='addstu'),
    # 添加班级
    url(r'addgrade/', views.addgrade, name='addgrade'),
    # 删除学生
    url(r'delstu/', views.delstu, name='delstu'),
    # 编辑学生
    url(r'editgrade/', views.editgrade, name='editgrade'),

    #测试
    url(r'test/',views.test,name='test')

]

django3/day01/day01/urls.py
from django.contrib import admin
from django.conf.urls import url,include

from django.contrib.staticfiles.urls import static

from day01 import settings

urlpatterns = [
    url(r'admin/', admin.site.urls),
    url(r'app/', include('app.urls',namespace='app')),
]
#把mieda目录变成static那样的静态目录
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django3/day01/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>
{% block extCSS %}
{% endblock %}

{% block extJS %}

{% endblock %}

{% block index_frameset %}

{% endblock %}

<body>

{% block content %}
{% endblock %}

{% block footer %}
{% endblock %}
</body>
</html>

django3/day01/templates/base_main.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block extJS %}
    <script type="text/javascript" src="/static/js/jquery.min.js"></script>
{% endblock %}

django3/day01/templates/grade.html
<!DOCTYPE HTML>
<html>
{% load staticfiles %}
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title></title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<meta name="generator" content="" />
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;">
<link href="{% static 'css/haiersoft.css' %}" rel="stylesheet" type="text/css" media="screen,print" />
<link href="{% static 'css/print.css' %}" rel="stylesheet" type="text/css"  media="print" />
<script src="{% static 'js/jquery-1.10.1.min.js' %}"></script>
<script src="{% static 'js/side.js' %}" type="text/javascript"></script>

<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<script src="http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js"></script>
<![endif]-->
</head>

<body>


<!-- MainForm -->
<div id="MainForm">
<div class="form_boxA">
<h2>班级信息列表</h2>
<table cellpadding="0" cellspacing="0">
<tr>
<th>序号</th>
<th>班级名称</th>
<th>创建时间</th>
<th>操作</th>
</tr>
    {% for grade in grades %}
<tr>
<td>{{ grade.id }}</td>
<td>{{ grade.g_name }}</td>
<td>{{ grade.g_create_time }}</td>
<td><a href="{% url 'app:editgrade' %}?grade_id={{ grade.id }}">编辑</a>
</tr>
    {% endfor %}
</table>
<p class="msg">共找到47条年度预算记录，当前显示从第1条至第10条</p>
</div>

<ul id="PageNum">
<li><a href="{% url 'app:grade' %}">首页</a></li>
{% if grades.has_previous %}
<li><a href="{% url 'app:grade' %}?page_num={{ grades.previous_page_number }}">上一页</a></li>
{% endif %}
    {% for i in grades.paginator.page_range %}
<li><a href="{% url 'app:grade' %}?page_num={{ i }}">{{ i }}</a></li>
    {% endfor %}
{% if grades.has_next %}
<li><a href="{% url 'app:grade' %}?page_num={{ grades.next_page_number }}">下一页</a></li>
{% endif %}
<li><a href="{% url 'app:grade' %}?page_num={{ grades.paginator.num_pages }}">尾页</a></li>
</ul>

</div>

</body>
</html>

django3/day01/templates/head.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
{% load staticfiles %}
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>头部</title>
<link rel="stylesheet" type="text/css" href="/static/css/public.css" />
<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/public.js' %}"></script>
</head>

<body>
	<!-- 头部 -->
	<div class="head">
		<div class="headL">
			<img class="headLogo" src="{% static 'img/logLOGO.png' %}"/>
		</div>
		<div class="headR">
			<span style="color:#FFF">欢迎：admin</span> <a href="/templates/head2.html" rel="external">【退出】</a>
		</div>
	</div>
</body>
</html>

django3/day01/templates/index.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>首页</title>
</head>
<frameset rows="100,*" cols="*" scrolling="No" framespacing="0"
	frameborder="no" border="0">
	<frame src="{% url 'app:head' %}" name="headmenu" id="mainFrame" title="mainFrame"><!-- 引用头部 -->
<!-- 引用左边和主体部分 -->
	<frameset rows="100*" cols="220,*" scrolling="No"
	framespacing="0" frameborder="no" border="0">
		<frame src="{% url 'app:left' %}" name="leftmenu" id="mainFrame" title="mainFrame">
		<frame src="{% url 'app:grade' %}" name="main" scrolling="yes" noresize="noresize"
	id="rightFrame" title="rightFrame">
	</frameset>
</frameset>
</html>

django3/day01/templates/left.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>首页左侧导航</title>
<link rel="stylesheet" type="text/css" href="/static/css/public.css" />
<script type="text/javascript" src="/static/js/jquery.min.js"></script>
<script type="text/javascript" src="/static/js/public.js"></script>
<head></head>

<body id="bg">
    {{ user.username }}
	<!-- 左边节点 -->
	<div class="container">

		<div class="leftsidebar_box">
			<a href="main.html" target="main"><div class="line">

					<img src="/static/img/coin01.png" />&nbsp;&nbsp;首页
				</div></a>
			<dl class="system_log">
				<dt>
					<img class="icon1" src="/static/img/coin03.png" /><img class="icon2"
						src="/static/img/coin04.png" /> 班级管理<img class="icon3"
						src="/static/img/coin19.png" /><img class="icon4"
						src="/static/img/coin20.png" />
				</dt>
                {% for p in user.r.r_p.all %}
                {% ifequal p.p_name 'GRADELIST' %}
				<dd>
					<img class="coin11" src="/static/img/coin111.png" /><img class="coin22"
						src="/static/img/coin222.png" />
					<a class="cks" href="{% url 'app:grade' %}"
						target="main">班级列表</a><img class="icon5" src="/static/img/coin21.png" />
				</dd>
                    {% endifequal %}
                    {% ifequal p.p_name 'GRADEADD' %}
				<dd>
					<img class="coin11" src="/static/img/coin111.png" /><img class="coin22"
						src="/static/img/coin222.png" />
					<a class="cks" href="{% url 'app:addgrade' %}"
						target="main">班级添加</a><img class="icon5" src="/static/img/coin21.png" />
				</dd>
                {% endifequal %}
                    {% endfor %}
			</dl>
			<dl class="system_log">
				<dt>
					<img class="icon1" src="/static/img/coin03.png" /><img class="icon2"
						src="/static/img/coin04.png" /> 学生管理<img class="icon3"
						src="/static/img/coin19.png" /><img class="icon4"
						src="/static/img/coin20.png" />
				</dt>
                {% for p in user.r.r_p.all  %}
                    {% ifequal p.p_name 'STUDENTLIST' %}
				<dd>
					<img class="coin11" src="/static/img/coin111.png" /><img class="coin22"
						src="/static/img/coin222.png" />
					<a class="cks" href="{% url 'app:student' %}"
						target="main">学生列表</a><img class="icon5" src="/static/img/coin21.png" />
				</dd>
                    {% endifequal %}
                    {% ifequal p.p_name 'STUDENTADD' %}
				<dd>
					<img class="coin11" src="/static/img/coin111.png" /><img class="coin22"
						src="/static/img/coin222.png" />
					<a class="cks" href="{% url 'app:addstu' %}"
						target="main">添加学生</a><img class="icon5" src="/static/img/coin21.png" />
				</dd>
                {% endifequal %}
                {% endfor %}


			</dl>
			<dl class="system_log">
				<dt>
					<img class="icon1" src="/static/img/coinL1.png" /><img class="icon2"
						src="/static/img/coinL2.png" /> 系统管理<img class="icon3"
						src="/static/img/coin19.png" /><img class="icon4"
						src="/static/img/coin20.png" />
				</dt>
				<dd>
					<img class="coin11" src="/static/img/coin111.png" /><img class="coin22"
						src="/static/img/coin222.png" /><a href="changepwd.html"
						target="main" class="cks">修改密码</a><img class="icon5"
						src="/static/img/coin21.png" />
				</dd>
				<dd>
					<img class="coin11" src="/static/img/coin111.png" /><img class="coin22"
						src="/static/img/coin222.png" /><a class="cks">退出</a><img
						class="icon5" src="/static/img/coin21.png" />
				</dd>
			</dl>

		</div>

	</div>
</body>
</html>

django3/day01/templates/login.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
{% load staticfiles %}
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>登录</title>
<link rel="stylesheet" type="text/css" href="{% static 'css/public.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/page.css' %}" />
<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/public.js' %}"></script>
</head>
<body>
<form action="" method="post">
    {% csrf_token %}
	<!-- 登录body -->
	<div class="logDiv">
		<img class="logBanner" src="{% static 'img/logBanner.png' %}" />
		<div class="logGet">
			<!-- 头部提示信息 -->
			<div class="logD logDtip">
				<p class="p1">登录</p>
			</div>
			<!-- 输入框 -->
			<div class="lgD">
				<img class="img1" src="{% static 'img/logName.png' %}" />
                <input type="text" name="username"
					placeholder="输入用户名" />
			</div>
			<div class="lgD">
				<img class="img1" src="{% static 'img/logPwd.png' %}" />
                <input type="text" name="password"
					placeholder="输入用户密码" />
			</div>
			<div class="logC">
				<a href="{% url 'app:index' %}" target="_self"><button>登 录</button></a>
			</div>
		</div>
	</div>
	<!-- 登录body  end -->

	<!-- 登录页面底部 -->
	<div class="logFoot">
		<p class="p1">版权所有：安徽公司公司</p>
		<p class="p2">123456789</p>
	</div>
	<!-- 登录页面底部end -->
</form>
</body>
</html>

django3/day01/templates/student.html
<!DOCTYPE HTML>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title></title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<meta name="generator" content="" />
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;">
<link href="/static/css/haiersoft.css" rel="stylesheet" type="text/css" media="screen,print" />
<link href="/static/css/print.css" rel="stylesheet" type="text/css"  media="print" />
<script src="/static/js/jquery-1.10.1.min.js"></script>
<script src="/static/js/side.js" type="text/javascript"></script>

<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<script src="http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js"></script>
<![endif]-->
</head>

<body>


<!-- MainForm -->
<div id="MainForm">
<div class="form_boxA">
<h2>学生信息列表</h2>
<table cellpadding="0" cellspacing="0">
<tr>
<th>序号</th>
<th>学生名称</th>
<th>学生头像</th>
<th>班级</th>
<th>操作</th>
</tr>
    {% for stu in stus %}
    <tr>
        <td>{{ stu.id }}</td>
        <td>{{ stu.s_name }}</td>
        <td><img src="/media/{{ stu.img }}" alt="" width="50"height="50"></td>
        <td>{{ stu.g.g_name}}</td>
        <td><a href="{% url 'app:delstu' %}?s_id={{ stu.id }}">删除</a></td>
    </tr>
    {% endfor %}

</table>
<p class="msg">共找到47条年度预算记录，当前显示从第1条至第10条</p>
</div>

<ul id="PageNum">
<li><a href="#">首页</a></li>
<li><a href="#">上一页</a></li>
<li><a href="#">1</a></li>
<li><a href="#">2</a></li>
<li><a href="#">3</a></li>
<li><a href="#">4</a></li>
<li><a href="#">5</a></li>
<li><a href="#">6</a></li>
<li><a href="#">下一页</a></li>
<li><a href="#">尾页</a></li>
</ul>

</div>

</body>
</html>